### ISSUE TITLE
Add license.

### ISSUE THREAD

**Issue by Masson-Apereo** [uw-x/watercomms#3]
I [read](https://underwatermessaging.cs.washington.edu/) that this software is open source, however I can not find an [OSI-Approved Open Source License](https://opensource.org/licenses/alphabetical), or any license, associated with this repository or project. 

If a license is not included in the repository, then the software code is--in many jurisdictions, including the U.S.--by default, "all rights reserved," meaning that no one can use it unless expressly permitted by the authors.

If you would like the project to be open source, please add an OSI license. Github provides best practices [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Comment by justinklchan** [comment]
We have added a license, thanks for bringing this to our attention.
